on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: "22.x"
  RUBY_VERSION: "3.0"
  LICENSE_FINDER_VERSION: "7.1.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install Yarn
        run: npm install --global yarn
        shell: bash

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false

      - name: Install License Finder
        shell: bash
        run: gem install license_finder:${{ env.LICENSE_FINDER_VERSION }} --no-document

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Check Licenses
        run: yarn license:check
        shell: bash

      - name: Lint
        run: yarn lint
        shell: bash

      - name: Check format
        run: yarn format:check
        shell: bash

      - name: Test Coverage
        run: yarn test:coverage
        shell: bash

      - name: Build
        run: yarn build
        shell: bash

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: ./packages/oidc-provider/dist
